### ISSUE TITLE
Consider copying .d.ts

### ISSUE THREAD

**Issue by blevine** [swimauger/tsc-hooks#11]
Hi,

Great little utility.  Thanks!  I'm wondering if there should be some way to allow type files (*.d.ts) to be copied. You could do this now by setting allowTS to true, but then all *.ts files would be copied which I'd rather not do.

**Comment by swimauger** [comment]
Hey @blevine,

Have you tried messing around with the include and exclude properties in config... Maybe something like this:

```json5
{
  "compilerOptions": {
    "allowTs": true
    // ...
  },
  "include": [ "src/**/*.d.ts" ],
  "exclude": [ "src/**/*.ts" ],
  "hooks": [ "copy-files" ]
  // ...
}
```

**Comment by blevine** [comment]
Good points.  I'll try that out.  Thanks

**Comment by blevine** [comment]
So I tried your suggestion, but ran into a few problems. The *.d.ts files weren't copied because of this line in copy-files.js:

`if (file.endsWith('.js') || (!this.tsconfig.compilerOptions?.allowTS && file.endsWith('.ts'))) continue;`

So I tried setting `compilerOptions.allowTS `to true in my tsconfig.json, but since that's a non-standard property, tsc complained with the following error:

> tsconfig.json:21:5 - error TS5025: Unknown compiler option 'allowTS'. Did you mean 'allowJs'?

**Comment by swimauger** [comment]
@blevine 
Alrighty I just pushed and published v1.1.0, give it a whirl, should resolve this issue

**Comment by sanqi377** [comment]
Hi,

i don't think i know how to use it. i want to copy *.wxss and *.wxml and *.json. the following configuration is not copied
```
"include": [
    "src/**/*.ts"
  ],
  "hooks": [
    "src/**/*.wxml",
    "src/**/*.wxss",
    "src/**/*.json"
  ]
```

what should i do?

**Comment by swimauger** [comment]
@sanqi377 try this
```json5
  "include": [
    "src/**/*.wxml",
    "src/**/*.wxss",
    "src/**/*.json"
  ],
  "hooks": [ "copy-files" ]
```

**Comment by sanqi377** [comment]
@swimauger 
t's a shame.
This error message appears：
No inputs were found in config file 'C:/Users/sanqi/Desktop/w-qui/tsconfig.json'. Specified 'include' paths were '["src/**/*.wxml","src/**/*.wxss","src/**/*.json"]' and 'exclude' paths were '["dist"]'.

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
  },
  "include": [
    "src/**/*.wxml",
    "src/**/*.wxss",
    "src/**/*.json",
    "src/**/*.ts",
  ],
  "hooks": [
    "copy-files"
  ]
}
```

This allows you to run. But still no effect
